// src/components/CopyrightPolicyPage.jsx
import React from 'react';
// FIX: Changed import path from '../components/LegalPageLayout' to './LegalPageLayout' 
//      (assuming both files are in src/components)
import LegalPageLayout from './LegalPageLayout'; 
import { Zap, Feather, Code, Layers, FileWarning } from 'lucide-react';

const CopyrightPolicyPage = () => {
  return (
    <LegalPageLayout 
      title="Copyright Policy" 
      // FIX: Added the missing required 'subtitle' prop
      subtitle="Framework for intellectual property, data licensing, and unauthorized use of portal assets."
      lastUpdated="October 20, 2025"
    >
      <p>
        <Feather size={16} className="inline mr-2 text-teal-500"/>
        This policy establishes the intellectual property framework for all assets deployed on the Yuva Saathi portal. It governs user-generated content, government data licenses, and the proper use of copyrighted materials in compliance with the **Indian Copyright Act, 1957**, and relevant government I.P. standards.
      </p>

      <h2>1. Ownership and Asset Categorization</h2>
      
      <h3>1.1 Government Copyright (The Core Asset)</h3>
      <p>
        The complete visual design, proprietary algorithms (e.g., skill-job matching engine), data schema, and unique textual content generated by the State Government are protected under copyright, held by the **Department of Labour Resources, Government of Bihar**. Reproduction without explicit, formal permission is strictly prohibited.
      </p>

      <h3>1.2 Open Source and Licensed Components <Code size={18} className="inline ml-2 text-blue-500"/></h3>
      <p>
        The Service integrates various open-source libraries (e.g., React, Tailwind CSS) under licenses such as MIT/Apache 2.0. The underlying system code for these components is not subject to Government copyright. Full attribution and compliance with their respective licenses are maintained in the service documentation.
      </p>

      <h3>1.3 Data Licensing (India Stack and API Data)</h3>
      <p>
        Data accessed or verified via **India Stack services (e.g., Aadhaar)** is governed by the licenses of the respective nodal authorities (e.g., UIDAI, MeitY). The data itself is not copyrighted by Yuva Saathi, but the structure, presentation, and aggregation of this data within the portal are the exclusive intellectual property of the Service.
      </p>

      <h2>2. Mandatory Attribution and Use of Emblems</h2>
      
      <h3>2.1 Attribution of Schemes and Programs</h3>
      <p>
        Any academic paper, presentation, or public work utilizing data, statistics, or visual output from the Yuva Saathi portal must include mandatory attribution in the format: **"Source: Yuva Saathi Portal, Department of Labour Resources, Government of Bihar."**
      </p>

      <h3>2.2 Proper Use of Logos and Emblems</h3>
      <p>
        The National Emblem, the Bihar State Emblem, and logos of co-branding schemes (e.g., PMKVY, Digital India) are protected by the **Emblems and Names (Prevention of Improper Use) Act, 1950**. These assets cannot be used for any private commercial activity or placed on any third-party marketing material without formal written clearance from the State's Nodal Authority.
      </p>
      
      <h2>3. User-Generated Content (UGC)</h2>
      <p>
        When a user uploads content (e.g., resume, project portfolio, employer reviews), the user retains the copyright to that content. However, by uploading, the user grants the Government of Bihar a **perpetual, non-exclusive, royalty-free, worldwide license** to store, display, and share that content for the purpose of facilitating employment and skill validation.
      </p>

      <h2>4. Digital Millennium Copyright Act (DMCA) Equivalent Reporting</h2>
      <p>
        <FileWarning size={16} className="inline mr-2 text-red-500"/>
        To report alleged copyright infringement, a formal, notarized notice must be sent to the **Nodal Grievance Officer** detailing:
      </p>
      <ol>
        <li>Proof of copyright ownership (Registration Certificate or equivalent legal document).</li>
        <li>A precise URL and description of the infringing material on the Service.</li>
        <li>A sworn statement that the use is unauthorized by the copyright owner.</li>
      </ol>
      <p>
        Upon receipt of a valid notice, the content will be subject to a 7-day review period, after which it may be temporarily disabled pending investigation.
      </p>

    </LegalPageLayout>
  );
};

export default CopyrightPolicyPage;